### ISSUE TITLE
Pretrained model not generating correct detections

### ISSUE THREAD

**Issue by sebamenabar** [facebookresearch/grid-feats-vqa#10]
Hi, I'm trying to load the weights to use in a detectron model. I installed as suggested on the README and using the following code:

```python3
import sys
sys.path.insert(0, "../grid-feats-vqa/")

import matplotlib.pyplot as plt
from PIL import Image

import torch
import torchvision.transforms as T

from extract_grid_feature import setup, extract_grid_feature_argument_parser
from detectron2.checkpoint import DetectionCheckpointer
from detectron2.modeling import build_model
from detectron2.utils.visualizer import Visualizer

%matplotlib inline

args = extract_grid_feature_argument_parser().parse_args(['--config-file', '../grid-feats-vqa/configs/R-50-grid.yaml'])
cfg = setup(args)
cfg.defrost()
cfg.MODEL.WEIGHTS = "../data/R-50.pth"
cfg.MODEL.DEVICE = 'cpu'
cfg.freeze()

model = build_model(cfg)
DetectionCheckpointer(model).resume_or_load(cfg.MODEL.WEIGHTS, resume=True);

path_to_coco_img = "/Users/sebamenabar/Documents/datasets/VQA/val2014/COCO_val2014_000000000136.jpg"
img = Image.open(path_to_coco_img).convert('RGB')
model.eval()
with torch.no_grad():
    outputs = model([{"image": T.functional.to_tensor(img)}])

v_gt = Visualizer(img, None)
v_gt = v_gt.overlay_instances(boxes=outputs[0]["instances"].pred_boxes)

fig, ax = plt.subplots(figsize=(10, 10))
ax.imshow(v_gt.get_image())
plt.show()
```

But this generates the following result:

![imagen](https://user-images.githubusercontent.com/13748963/85872190-6c1fe700-b79d-11ea-8f87-6fc42b2712b6.png)

Which does not look like a correct detection.
Any chance you could help me with this?

**Comment by endernewton** [comment]
It depends on what you want.

1. If you want to use grid features to do detection, I suspect the result will actually be something like this (I haven't done visualization myself), but this is expected as the detection result is indeed not as good. The grid features are meant for down-stream tasks, not detection.
2. If you want to do object detection with VG, please use the yaml file '*-updn.yaml' to train a detector yourself, it should give reasonable detection outputs.

**Comment by luo3300612** [comment]
If you use `build_detection_test_loader_with_attributes` like in `extract_grid_feature.py` to load this image, pretrained model will give more reasonable detection outputs.
![image](https://user-images.githubusercontent.com/28670791/87388490-70694400-c594-11ea-8da2-28611cfaddc5.png)

**Comment by LYuhang** [comment]
@luo3300612 Hello, can you give out the code that can produce the following reasonable outputs. I want to write a image loader for my VQA project. I can't realy understand the code in `extract_grid_feature.py`. I would greatly appreciate it.

> If you use `build_detection_test_loader_with_attributes` like in `extract_grid_feature.py` to load this image, pretrained model will give more reasonable detection outputs.
> ![image](https://user-images.githubusercontent.com/28670791/87388490-70694400-c594-11ea-8da2-28611cfaddc5.png)
