### ISSUE TITLE
Pretrained weight for BUTD model

### ISSUE THREAD

**Issue by j-min** [facebookresearch/grid-feats-vqa#11]
Hello, thanks for sharing your implementations.

Could you please also share the weights for the pretrained BUTD model trained on visual genome?

**Comment by playerkk** [comment]
Thanks for your interest in our work. We mainly used Pythia, which is similar to BUTD but not exactly the same, for VQA in our paper.

**Comment by endernewton** [comment]
Hi @j-min, what you are looking for for pretrained BUTD? we have config files for BUTD pre-training but that is based on R-50 so it probably won't be as useful as the standard BUTD features pre-trained on R-101. If you are looking for a more powerful model for regions, we can train one. If you are looking for a fair comparison between grid/regions, you can also train one yourself using R-50 config.
