### ISSUE TITLE
R-50 VG weights give worse performance than Imagenet weights

### ISSUE THREAD

**Issue by kawshik8** [facebookresearch/grid-feats-vqa#15]
I tried to plug in the R-50 pretrained model weights into a torchvision resnet50 model using a simple pattern matching script
However this does not seem to improve performance as expected and in fact performs worse than image net weights for image size 448 x 448 in an MCAN type model (custom implementation - where I replace LSTM with a BERT and dont use Self attention on top of language features) 

Am I using the weights wrong?

**Comment by endernewton** [comment]
Did you try the released features directly for MCAN? Did you do it on VQA or other task? That can help debugging. However, we are not supposed to debug for you, so expect slow response here.

**Comment by kawshik8** [comment]
No I generated grid features during training and trained it end to end. Yes it was on VQA. Yes I understand. I just wanted to know if directly loading your pretrained model's weights into torchvision resnet50 model's state dict would work as a csutom grid feature extractor?

**Comment by endernewton** [comment]
We haven't tried directly using it in to torchvision models but it would be interesting to know (I guess it should show some improvements over image-net pre-trained ones). one thing you can try (to debug) is to extract the grid features using this code base (use the 448x448 size) and using torchvision, and see if there is a difference. If so, there is a bug.

**Comment by kawshik8** [comment]
oh ok yeah makes sense. I'll try it out and get back to you then I guess. Thanks!

**Comment by playerkk** [comment]
Another factor that may cause the discrepancy is the pixel mean and std values. The values used by Detectron2 (and hence this repo) are different from torchvision. https://github.com/facebookresearch/detectron2/blob/master/detectron2/config/defaults.py#L35-L42

**Comment by kawshik8** [comment]
oh interesting. I'll try this out too thanks!

**Comment by endernewton** [comment]
Any updates? I am thinking we can upload it to pytorch so that one can directly get the weights like ImageNet pre-trained ones.

**Comment by kawshik8** [comment]
No, I haven't been able to work on it for a while... nor will I for some time in the future I guess

**Comment by endernewton** [comment]
Okay, then closing this for now. You can comment once you have a clear signal.
