### ISSUE TITLE
unexpected behaviour of extract_region_feature.py

### ISSUE THREAD

**Issue by rizavelioglu** [facebookresearch/grid-feats-vqa#16]
@endernewton 
When using `extract_region_feature.py` in this PR: [facebookresearch/grid-feats-vqa#3](https://github.com/facebookresearch/grid-feats-vqa/pull/3) to extract features of Hateful Memes dataset, no object's detected for some images (**e.g.** `01243.png`). Is this an expected behaviour?

Check out this [Colab notebook](https://colab.research.google.com/drive/1pPPItI7tUIL751-xApoQoVZHDEcDQqDx?usp=sharing) to see the details. 

I used another model from Detectron2 and detected an object on the same image (`01243.png`)

**Comment by endernewton** [comment]
@vedanuj? I cannot run the colab unfortunately, it seems to miss memes images.

**Comment by rizavelioglu** [comment]
Hey, thank you for your reply!

> I cannot run the colab unfortunately, it seems to miss memes images.

Yes, since it's forbidden to share the images from the Hateful Memes dataset, I can not share it here (one needs to download them on its own). But I just wanted to share the notebook so that one can see the output when running the script on a custom dataset, it does not detect any object in some of the images. Then just to show there's nothing wrong the images, I run a D2 model on the same images and get the predictions

**Comment by GaryYufei** [comment]
Hi, I also have some concerns regarding ``extract_region_feature.py''  in this PR: facebookresearch/grid-feats-vqa#3:

In the up-down model, the VG objects are extracted such that every image has 10-100 boxes (called adaptive features). Yet, I found no similar constraints here and the output VG boxes are normally less than 10. Any thoughts on this?

**Comment by vedanuj** [comment]
Please check the response to #19 and let us know if that solution helps.
