### ISSUE TITLE
scriptable code

### ISSUE THREAD

**Issue by aryan461** [facebookresearch/grid-feats-vqa#17]
I want to make a script of the code, with TorchScript. Since the detecron2 version that is used in this project is not scriptable, I tried to use the last version of D2. But I got an error:

`TypeError: __init__() got an unexpected keyword argument 'train_on_pred_boxes'`

@endernewton
What do you suggest? 
Is there any way to use the new D2? or is there any other way for scripting?

**Comment by 1693332810** [comment]
I also encountered the same problem, have you solved it?

**Comment by aryan461** [comment]
> I also encountered the same problem, have you solved it?

No I couldn't. I've tried to save backbone and use weights in another code. I tried scriting layer to layer & also try to change D2. Anybody?

**Comment by endernewton** [comment]
Did not keep track of the D2 updates lately, previously I have tried to integrate D2 (see https://github.com/facebookresearch/grid-feats-vqa/commit/d9a14fbb7580fb377353d8b397c5a8e5443b4117), but ended up reverting it as D2 can be changed further.

Maybe some of you can refer to that code and find a working solution? You can open a PR for this if you can reproduce the results (especially the pre-trained model/features)

**Comment by aryan461** [comment]
@endernewton thank you very much for sharing and suggesting [d9a14fb](https://github.com/facebookresearch/grid-feats-vqa/commit/d9a14fbb7580fb377353d8b397c5a8e5443b4117). With your help and D2 contributers helps I could finally script the resnet backbone. you can find the codes [here](https://github.com/facebookresearch/detectron2/issues/2266#issuecomment-729545345).
