### ISSUE TITLE
train_net error:detectron2(version:0.1.1) RuntimeError

### ISSUE THREAD

**Issue by orangehc** [facebookresearch/grid-feats-vqa#18]
Not compiled with GPU support (ROIAlign_forward at /home/oliver/PycharmProjects/detectron2/detectron2/layers/csrc/ROIAlign/ROIAlign.h:73)
I have searched the error in the Internet but still can't slove the problem, and I am sure my cuda and the version of pytorch, etc. are right. Would you have any idea or suggestion to slove the problem? Thanks.

**Comment by orangehc** [comment]
I sloved it by myself today costing me much time. In my opinion, the problem will happen because the PATH of CUDA HOME. At the grid-feats repo, giving the detectron2 which is a special version(other versions can't use in the repo) and only giving the install way is online install which can't show the same problem when installing in local. If you install the detectron2 from local,  you will find where causing the problem maybe.

**Comment by endernewton** [comment]
Thanks @orangehc!
