### ISSUE TITLE
Issues with extract_region_feature.py

### ISSUE THREAD

**Issue by GaryYufei** [facebookresearch/grid-feats-vqa#19]
Hi, Thanks for the great work.

In the up-down model, the VG objects are extracted such that every image has 10-100 boxes (called adaptive features). Yet, I found no similar constraints here and the output VG boxes are normally less than 10. (I tried images from open images)

Any thoughts on this?

**Comment by endernewton** [comment]
@vedanuj ?

**Comment by vedanuj** [comment]
@GaryYufei In order to get all the bboxes you can set `MODEL.ROI_HEADS.SCORE_THRESH_TEST=0` while running the extraction. Currently that threshold is set to D2's default threshold of 0.05 and hence you get only the higher confidence boxes. Let us know if that works for you.

**Comment by GaryYufei** [comment]
Hi @endernewton @vedanuj  Thanks for your reply.

I note that you provide downloadable region features and clearly those features are in the range of [10, 100]. Which configuration files you used to extract those features? Just setting  MODEL.ROI_HEADS.SCORE_THRESH_TEST=0? As some images have more than 100 boxes before the pruning.

Many thanks for your help!

**Comment by GaryYufei** [comment]
Hi @endernewton @vedanuj , I have tried to set MODEL.ROI_HEADS.SCORE_THRESH_TEST=0 and I indeed get 100 boxes. However, many of these 100 boxes are duplicated as shown in r_indices. I am wondering if you could release the configuration files used to produce the downloadable pretrained features? 

Many thanks!

**Comment by Cuberick-Orion** [comment]
I am a bit confused... because, I couldn't find the `extract_region_feature.py`... Did I miss something?

**Comment by Cuberick-Orion** [comment]
> I am a bit confused... because, I couldn't find the `extract_region_feature.py`... Did I miss something?

Never mind, sorry. Saw the pull request...

**Comment by endernewton** [comment]
I think you can change the NMS threshold to deduplicate. Thanks!
