### ISSUE TITLE
How to extract region feature?

### ISSUE THREAD

**Issue by orangehc** [facebookresearch/grid-feats-vqa#22]
I didn't find the extract_region_feature.py in the repo and I found someone has questions about the python file in issues. Now, I have need to extract region feature after training the model on 'R-50-updn.yaml' and don't know how to do it.  Could anyone help me solve the problem?  Thanks.

**Comment by endernewton** [comment]
It is in the PR #3. However, this is experimental code, and have not merged with the main branch yet.
