### ISSUE TITLE
How do you control input image size and feature number？

### ISSUE THREAD

**Issue by ParadoxZW** [facebookresearch/grid-feats-vqa#23]
I am confused about the description of input size controlling in the paper,
> Notably, input images are resized to have a maximum shorter side of 600 pixels (longest 1000) when keeping aspect ratio fixed.

My understanding is that images (from Visual Genome) are resized and padded (Is there a padding process?) to 600X1000 when training the detector. So I guess that, when training a VQA model, images (from MSCOCO) are also resized and padded to 600X1000. But there are two questions:
+ What is the specific procedure of resizing and padding？And is there actually two type image size，i.e. 600X1000 and 1000X600, since both of them will output 608 features and can be used by VQA model like MCAN? But when I read your code (`extract_grid_feature.py`), there is no sign of resizing and padding, just the normalization of pixel values.
+ I found that maximum image size in MSCOCO is 640X640, so do we actually enlarge every image in MSCOCO when training a VQA model using 608 features?

**Comment by endernewton** [comment]
My understanding is that the largest possible size is 600x1000, so it could be 300x1000 depending on the input image aspect ratio. The detailed steps are found in D2's code base. Note that when used for VQA models, the spatial dimensions are flattened, so it only needs to take the maximum possible # of features. See example at: https://mmf.sh/docs/projects/movie_mcan/

**Comment by ParadoxZW** [comment]
Is there resize procedure when training a VQA model, or just use the original image without resizing?

**Comment by ParadoxZW** [comment]
I've read the code of preprocess in Detectron2

```Python
scale = size * 1.0 / min(h, w)
if h < w:
    newh, neww = size, scale * w
else:
    newh, neww = scale * h, size
if max(newh, neww) > self.max_size:
    scale = self.max_size * 1.0 / max(newh, neww)
    newh = newh * scale
    neww = neww * scale
neww = int(neww + 0.5)
newh = int(newh + 0.5)
```

It means there are two types largest size of images, i.e. 600X1000 and 1000X600. Training a VQA model using pre-extracted features is fine, because feature maps are flattened before input to a model like MCAN. But there is a trouble when training a end-to-end model, since the batch of samples should input to a CNN but there may be different image sizes in a batch (and padding cannot fix this problem otherwise the image size will be padded to 1000X1000). May I ask how you deal with this problem?

**Comment by gedaye11** [comment]
Have you solved this problem yet? How to solve it?
Thanks.
