### ISSUE TITLE
[Help] Can I use the pretrained models for Region Features

### ISSUE THREAD

**Issue by mineshmathew** [facebookresearch/grid-feats-vqa#27]
@endernewton 
Hi I landed here while searching for a pre-trained object detection model , trained on VisualGenome using detectron2.
Can I use the models you have listed and get features from say the FC layers of the box head?
What I need actually is to extract region features of objects as done in most VQA models like Pythia

**Comment by endernewton** [comment]
You can check this PR: https://github.com/facebookresearch/grid-feats-vqa/pull/3
