### ISSUE TITLE
How to extract grid features on customized images?

### ISSUE THREAD

**Issue by SweetIncubus** [facebookresearch/grid-feats-vqa#30]
Hi~
I have some customized images and I want to extract their grid features. But I don't know how to do that with code.
Could you tell me?
Thank you!

**Comment by endernewton** [comment]
You can start from this script? https://github.com/facebookresearch/grid-feats-vqa/blob/master/extract_grid_feature.py The code is pretty simple and self-explanatory.

**Comment by Fly2flies** [comment]
> You can start from this script? https://github.com/facebookresearch/grid-feats-vqa/blob/master/extract_grid_feature.py The code is pretty simple and self-explanatory.

Hi~ After check the code provided, I want to confirm one things: should the channel order of the input image be 'BGR' ?
