### ISSUE TITLE
I run extract_grid_feature.py and loop over my dataset but got most 0 in outputs

### ISSUE THREAD

**Issue by waizei** [facebookresearch/grid-feats-vqa#31]
i have no idea to figure that

**Comment by endernewton** [comment]
Oh which images you are running it on? We are not supposed to debug for you though.

**Comment by waizei** [comment]
> Oh which images you are running it on? We are not supposed to debug for you though.

I use  TextVQA dataset,Is it related to the size of the image?

**Comment by gedaye11** [comment]
你好，请问您有解决该问题吗？不太清楚如何处理非coco数据集的初始图像size。
