### ISSUE TITLE
WARNING: Did not find branch or tag 'ffff8ac', assuming revision or ref.

### ISSUE THREAD

**Issue by 1144181135** [facebookresearch/grid-feats-vqa#32]
I try to follow the command "python -m pip install 'git+https://github.com/facebookresearch/detectron2.git@ffff8ac'" to install detectron2, but find "WARNING: Did not find branch or tag 'ffff8ac', assuming revision or ref."

**Comment by endernewton** [comment]
I think it is there: https://github.com/facebookresearch/detectron2/tree/ffff8acc35ea88ad1cb1806ab0f00b4c1c5dbfd9
