### ISSUE TITLE
Did you try to training an end-to-end model?

### ISSUE THREAD

**Issue by ParadoxZW** [facebookresearch/grid-feats-vqa#5]
Did you try to training an end-to-end model, by composing your pretrained CNN model and some SOTA VQA model? Is the performance of these kind of models worse than just using CNN as a feature extractor?

**Comment by playerkk** [comment]
We tried end-to-end training using the Pythia model. We got better results than simply using a fixed feature extractor. See Table 7 of our paper https://arxiv.org/pdf/2001.03615.pdf.
