### ISSUE TITLE
resnet 101 backbone

### ISSUE THREAD

**Issue by luo3300612** [facebookresearch/grid-feats-vqa#8]
Thank you for your repo. How can I train on VG with a resnet 101 backbone like in [bottom-up-attention](https://github.com/peteanderson80/bottom-up-attention)?

**Comment by endernewton** [comment]
Just change 50 to 101 in this config and run it. https://github.com/facebookresearch/grid-feats-vqa/blob/master/configs/R-50-updn.yaml
